version: '3'
services:
  goapp:
 #   image: 716586613247.dkr.ecr.eu-north-1.amazonaws.com/go-app:1.0
    depends_on:
      - postgresdb
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - 80:8080
    container_name: goapp
    networks:
      - go-app-network
    volumes:
      - ./:/app
  postgresdb:
    image: postgres
    container_name: postgress 
    hostname: postgresdb 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - go-app-volume:/var/lib/postgresql/data
    networks:
      - go-app-network
  redisdb:
    image: redis
    ports:
      - 6379:6379
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  go-app-volume:
    driver: local
  jenkins-home:

networks:
  go-app-network:
